# Generated by Django 5.0.6 on 2024-05-26 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_imaeg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imaeg',
            new_name='image',
        ),
    ]
